version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: ghcr.io/dragonflydb/dragonfly:v1.27.2-ubuntu
    volumes:
      - /data/redis-${REDIS_NAME}:/data
    restart: unless-stopped
